### ISSUE TITLE
Extraneous dependencies at runtime

### ISSUE THREAD

**Issue by crshnburn** [IBM/JSONata4Java#117]
#97 has added the bnd-maven-plugin as a dependency which is then pulled in by every project that adds JSONata4Java as a dependency.

As this plug-in is only required for building the jar file could this be removed from the dependencies to reduce the dependency tree of this project.

**Comment by crshnburn** [comment]
Resolved by #124 @wnm3 what's the outlook on getting 1.4.7 pushed up to maven central?

**Comment by wnm3** [comment]
I'll be pushing 1.4.8 to maven central today.

**Comment by wnm3** [comment]
If this problem is resolved in version 1.4.8 to be released soon, please close this issue.

**Comment by crshnburn** [comment]
All working in 1.4.8.
