### ISSUE TITLE
Error with "Combines the key/value pairs into a single object"

### ISSUE THREAD

**Issue by fmossott** [IBM/JSONata4Java#121]
The following scenario is not working as expected (with both 1.4.3 and 1.4.6)

Starting with this JSON
```
{
    "var1": "val1",
    "var2": {
        "firstName": "John",
        "lastName": "doe",
        "age": 26,
        "address": {
            "streetAddress": "naist street",
            "city": "Nara",
            "postalCode": "630-0192"
        },
        "phoneNumbers": [
            {
                "type": "iPhone",
                "number": "0123-4567-8888"
            },
            {
                "type": "home",
                "number": "0123-4567-8910"
            }
        ]
    },
    "var3": {
        "firstName": "Paul",
        "lastName": "Smith",
        "age": 32,
        "address": {
            "streetAddress": "main avenue",
            "city": "Smart City",
            "postalCode": "234-234"
        },
        "phoneNumbers": [
            {
                "type": "Android",
                "number": "0123-4567-9999"
            },
            {
                "type": "office",
                "number": "0123-4567-2222"
            }
        ]
    }
}
```

I use this expression
```
var3.phoneNumbers{type:number}
```

that on try.jsonata.org results in the following, that is what I was trying to achieve
```
{
  "Android": "0123-4567-9999",
  "office": "0123-4567-2222"
}
```

This is documented on https://docs.jsonata.org/construction

On JSONata4Java (1.4.3 and 1.4.6) the result is
```
[
  {
    "type": "Android",
    "number": "0123-4567-9999"
  },
  {
    "type": "office",
    "number": "0123-4567-2222"
  }
]
```

Thanks you.

**Comment by wnm3** [comment]
At present the parser is not recognizing the {...} following phone number so it isn't being processed and instead we are simply executing var3.phoneNumbers

I hope to be able to extend the parser to recognize this pattern, but I'll need some dedicated time as I expect changing the parser will introduce many side effects.

**Comment by wnm3** [comment]
I believe this issue is fixed. Please check version 1.5.5 being released today and if you believe it is fixed, please close this issue. Thank you.

**Comment by fmossott** [comment]
Tested successfully with 1.5.5 and 1.5.7.
Thanks
