### ISSUE TITLE
java.util.NoSuchElementException

### ISSUE THREAD

**Issue by TejaswiniAnilPakhare** [IBM/JSONata4Java#125]
Scenario: While load testing application using JsonAta4Java jar getting exception NoSuchElementException. Can anyone please provide cause for this exception, as this issue is occurring only while load testing, single run for same application gives proper expected output.

java.util.NoSuchElementException: null
at java.util.LinkedList.removeFirst(LinkedList.java:270) ~[na:1.8.0_131]
at java.util.LinkedList.pop(LinkedList.java:801) ~[na:1.8.0_131]

**Comment by wnm3** [comment]
Sorry for taking a while to look into this. Unfortunately, I can't tell from the stack trace posted which stack/code was causing the issue so I'm reviewing all the .pop operations to see if I can check that the stack is not empty, to avoid the NPE. Out of curiosity, how are your performing the stress test. Perhaps I can recreate the situation? If it is easier to email to me, my email is wnm3@us.ibm.com.

**Comment by wnm3** [comment]
I'm checking in some updates in preparation for release 1.4.8 that includes changes to ExpressionVisitor.java and FrameEnvironment.java that added checks to ensure we don't pop an empty queue that results in the NoSuchElementException.

**Comment by wnm3** [comment]
If this problem is resolved in version 1.4.8 to be released soon, please close this issue.

**Comment by TejaswiniAnilPakhare** [comment]
Thank you for the fixes will check and close the issue. One curious question, can we use poll instead of pop  ?

**Comment by wnm3** [comment]
The FrameEnvironment has a peekContext() method to let you see what you would get (or null if empty).

**Comment by linehammer** [comment]
The NoSuchElementException in Java is thrown when one tries to access an iterable beyond its maximum limit. This means that, this exception is thrown by various accessor methods to indicate that the element being requested does not exist. The next() method in Java returns the next element in the iteration or [NoSuchElementException](http://net-informations.com/java/err/elements.htm) if the iteration has no more elements. The solution to this exception is to check whether the next position of an iterable is filled or empty . The following methods are used to check the next position:

- hasNext()
- hasMoreElements()

**Comment by wnm3** [comment]
Since we are trying to parallel the behavior of https://jsonata.org we return null to signify ** no match ** when accessing beyond the end of an array.
![image](https://user-images.githubusercontent.com/1359024/102630518-a5b52780-411a-11eb-874b-ff060b933da2.png)

I could look to add hasNext() to the FrameEnvironment if desired. But we should not throw a Java specific exception as that would break from the jsonata behavior.
