### ISSUE TITLE
Ternary operator returns predicate instead of expression

### ISSUE THREAD

**Issue by robertvanloenhout** [IBM/JSONata4Java#127]
When I use a ternary operator with a non-boolean predicate, then it returns the evaluated predicate, instead of applying the $boolean function and returning the correct evaluated expression.

Input:
```
{
  "key": "value"
}
```
JSONata:
```
key ? 1 : 2
```

Expected result is 1. Actual result is "value"

References:
https://docs.jsonata.org/programming#conditional-logic
https://docs.jsonata.org/boolean-functions#boolean

**Comment by wnm3** [comment]
I've fixed this in the code. You'll need to rebuild the jar file using mvn clean install until I push a new version to the Maven Central Repository. If you agree the problem is fixed, please close.

**Comment by robertvanloenhout** [comment]
I'm getting the expected result. Closing issue.
