### ISSUE TITLE
Map function is too strict with 1st argument

### ISSUE THREAD

**Issue by robertvanloenhout** [IBM/JSONata4Java#128]
Map function throws an EvaluateRuntimeException when the 1st argument is not an array.
This is not the same as jsonata.org where you can pass an object as the 1st argument.
It is very easy to encounter this problem, because when you filter on an array, it is returned
as a single object when there is only one object that meets the criteria (see example).
My request is to wrap the object automatically in an array as input for the map function.

Example input:
```
[
  {
    "key": "value1",
    "include": true
  },
  {
    "key": "value2",
    "include": false
  }
]
```
JSONata:
```
$map($[include = true], function($v, $i, $a) {
    $v.key
})
```
Expected result: "value1". Actual result: EvaluateRuntimeException

**Comment by wnm3** [comment]
I've fixed this in the code. You'll need to rebuild the jar file using mvn clean install until I push a new version to the Maven Central Repository. If you agree the problem is fixed, please close.

**Comment by robertvanloenhout** [comment]
I'm getting the expected result. Closing issue.
