### ISSUE TITLE
Unable to check existence of non-leaf object

### ISSUE THREAD

**Issue by robertvanloenhout** [IBM/JSONata4Java#129]
I am unable to check the existance of a non-leaf object comparing it to not null.
The non-leaf object seems to be equal to null always.

Example input:
```
{
  "parent": {
    "key": "value"
  }
}
```
JSONata:
```
parent != null ? "a" : "b"
```
Expected result: "a". Actual result: "b"

**Comment by wnm3** [comment]
I've fixed this in the code. You'll need to rebuild the jar file using mvn clean install until I push a new version to the Maven Central Repository. If you agree the problem is fixed, please close.

**Comment by robertvanloenhout** [comment]
I'm getting the expected result. Closing issue.
