### ISSUE TITLE
Null pointer error when trying to loop an array containing empty object

### ISSUE THREAD

**Issue by akshatha45** [IBM/JSONata4Java#137]
The following scenario is not working with 1.4.9

The Data used is : 

```json 
{
  "data": {
    "type": "Horror",
    "title": "ABCD",
    "cast": [
      {
        "fullName": "SOMENAME",
        "role" : "Hero",
        "birthDetails": {
          "address": {},
          "date": "1990-02-14",
          "country": "ES"
        }
      },
      {
        "fullName": "SOMENAME",
        "role" : "Heroine",
        "birthDetails": {
          "address": {},
          "date": "1993-02-14",
          "country": "ES"
        }
      },
      {
        "fullName": "SOMENAME",
        "role" : "Director",
        "birthDetails": {
          "address": {
            "stree1" : "234B, LHS",
            "street2" : "knh street",
            "pincode" : "JH15 7IY"
          },
          "date": "1990-02-14",
          "country": "ES"
        }
      }
    ]
  }
} 
```

 Below is the expression used : 

```
(
    $constructCast:= function($cast)
    {
        {
            "name" : $cast.fullName
        }
    };
 {
     "title" : "data.title",
     "cast" : $map(data.cast, $constructCast)
 }   
)
```
This is resulting in null pointer exception when using with JSONata4Java and works fine in https://try.jsonata.org/ 
Expecting it to evaluate and produce result 

```json
{
  "title": "data.title",
  "cast": [
    {
      "name": "SOMENAME"
    },
    {
      "name": "SOMENAME"
    },
    {
      "name": "SOMENAME"
    }
  ]
}
```

**Comment by wnmills3** [comment]
Thank you for finding this. The fix is in FunctionUtils.java line 559 to add a test for the ftc.children != null as shown below:
		if (flc.children != null && flc.children.size() > 0) {
I have to back out a change I'd made for the SumFunction before I check in this fix but it should be very soon.

**Comment by wnm3** [comment]
I've checked in this change and released version 1.5.0 that also reverted some changes for SumFunction to go back to returning a Long consistently. It will show up in Maven Central in a few hours.

**Comment by wnm3** [comment]
If you agree this problem is resolved, please close this issue.

**Comment by akshatha45** [comment]
The problem is resolved. Thanks for the fix.
