### ISSUE TITLE
Implement $distinct

### ISSUE THREAD

**Issue by mattbrain** [IBM/JSONata4Java#147]
I see this is a duplicate of 63 and 75 (which are closed) but I don't believe it has been implemented.

I get the error `Unknown function: $distinct` when attempting to call this with an array as the parameter.

**Comment by wnm3** [comment]
Thanks Matt, you are correct. Not sure why this was closed. Will try to implement tomorrow. Will let you know where I stand.

**Comment by mattbrain** [comment]
Fantastic, thanks for letting me know.

Cheers

Matt

**Comment by wnm3** [comment]
I've checked in the code and will release version 1.5.5 later today. Thanks
You can build it using mvn clean install from the command line in the JSONata4Java project directory (where the pom.xml file is).

**Comment by mattbrain** [comment]
Smoke test as below works great:
