### ISSUE TITLE
Expected parsing errors but parsed correctly

### ISSUE THREAD

**Issue by tacomalfoy** [IBM/JSONata4Java#156]
Hi!
I've found some discrepancies between this library (1.5.7) and what I experience using the JSONata exerciser.
There are some expressions raising a Syntax Error on the exerciser but that are correctly parsed on JSONata4Java.
I have also prepared a small test suite in order to better understand what I was expecting to obtain:
```java
public class ParsingErrorsTest {

    @Test
    void testUnknownOperator() {
        assertThrows(ParseException.class,
                () -> Expressions.parse("someField = 0 unknown_op someField = 1"),
                "Invalid operator: unknown_op has been used and no exception has been thrown.");
    }

    @Test
    void testSequenceOperatorsTakenAsOperands() {
        assertThrows(ParseException.class,
                () -> Expressions.parse("someField = 0 and or someField = 1"),
                "Another operator is expected after 'or': " +
                        "operand found instead and no exception has been thrown.");
    }
}
```
Am I missing something? Is this something known?
Thanks in advance for your help, and if you need further details just ask. 👍 

Best regards,
Luigi

**Comment by wnm3** [comment]
For Java we are using the ANTLR 4.0 parsing library so there are some situations where the language definition may believe the statement to be correct. In cases like these we try to catch malformed expressions with runtime errors. jsonata.js uses a different parsing approach so can better report errors like this.

I'll look at the language definition to see if we can disallow the invalid operator or at least throw the runtime exception. 

Thank you for identifying this problem.

**Comment by wnm3** [comment]
So, addressing this problem has raised some side effects I've been avoiding for too long so I'm trying to address them now. In order to ensure the parser processed the entire line I had to add a rule like:
```
expr_to_eof : expr EOF ;
```
and change the parsing to call the resulting expr_to_eof method in lieu of the expr method. The system now reports a syntax error for on in a statement like:
```
true and or false
```
The impact is non-trivial so it may be a while before I can release the fix for this but I'd like to get it done as there are other issues that are on hold pending parsing the entire input line...

I'll keep you posted. Thanks again.

**Comment by wnm3** [comment]
I'd received help from this stackoverflow [question](https://stackoverflow.com/questions/67908640/antlr-parser-to-throw-exception-for-true-and-or-false-statement/67909844#67909844).

**Comment by wnm3** [comment]
I just pushed version 1.5.8 to Maven Central (it will take a few hours to show up). Check [here](https://search.maven.org/search?q=g:com.ibm.jsonata4java) for version 1.5.8...

Please close this issue if you believe it has been fixed. Thank you.

**Comment by tacomalfoy** [comment]
I will try it with my scenario-specific test suite in order to validate the solution.
Thanks for the blazing fast support.

**Comment by tacomalfoy** [comment]
Everything seems to work fine in our scenarios after the update to 1.5.8.
Thanks again for the support.
