### ISSUE TITLE
ISO-8601 error message contains "foo"

### ISSUE THREAD

**Issue by robertvanloenhout** [IBM/JSONata4Java#157]
/com/api/jsonata4java/expressions/utils/Constants.java:278 
```
public static final String ERR_MSG_TO_MILLIS_ISO_8601_FORMAT = "The argument for the $toMillis function must be an ISO 8601 format datetime string: \"foo\"";
```
should be changed to
```
public static final String ERR_MSG_TO_MILLIS_ISO_8601_FORMAT = "The argument for the $toMillis function must be an ISO 8601 format datetime string: \"%s\"";
```
The String format call already passes the timestamp.

**Comment by wnm3** [comment]
I just pushed version 1.5.8 to Maven Central (it will take a few hours to show up). Check [here](https://search.maven.org/search?q=g:com.ibm.jsonata4java) for version 1.5.8...

Please close this issue if you believe it has been fixed. Thank you.

**Comment by robertvanloenhout** [comment]
I tested with 1.5.8 and the issue has been fixed. Thanks!
