### ISSUE TITLE
DateTimeParseException when using $toMillis

### ISSUE THREAD

**Issue by robertvanloenhout** [IBM/JSONata4Java#158]
When you use $toMillis on a date without time, a DateTimeParseException/EvaluateRuntimeException occurs.

Example input json:
```
{
  "date": "2021-08-25"
}
```

Example jsonata:
```
$toMillis(date)
```

Expected output as on https://try.jsonata.org/
```
1629849600000
```

**Comment by wnm3** [comment]
I just pushed version 1.5.8 to Maven Central (it will take a few hours to show up). Check [here](https://search.maven.org/search?q=g:com.ibm.jsonata4java) for version 1.5.8...

Please close this issue if you believe it has been fixed. Thank you.

**Comment by robertvanloenhout** [comment]
I tested with 1.5.8 and the issue has been fixed. Thanks!
