### ISSUE TITLE
!= null check returns false when expected true

### ISSUE THREAD

**Issue by JDUNNIN** [IBM/JSONata4Java#163]
GIVEN the JSON:
```
{
  "Error": {
    "message": "x"
  }
}
```
WHEN I evaluate the JSON against an expression:
```
Error != null
```
THEN I should get a `true` result as in JSONata exerciser.

Instead if always evaluates as `false` (or it might actually be `null` ?). This may be limited to null checks as numerics seemed to be OK. `x = x` appears to work OK, just not equals causing issue.

**Comment by wnm3** [comment]
I used the Tester configured with your object (will check in as dataobject_a.json) and it seemed to work as you expected:
Attempting to load JSON from file: dataobject_a.json
```
Using json:
{
  "Error" : {
    "message" : "x"
  }
}
Enter jsonata expression (or q to quit):
Error != null
true
```

**Comment by JDUNNIN** [comment]
Hmm odd - I will try see if I can diagnose more.

**Comment by JDUNNIN** [comment]
I wrote some more test cases around this trying to keep them minimal and it seems to produce the same result that it can't resolve `null` when it is checked. This screenshot shows the test cases on left side, each `Given`, `When`, `Then` corresponds to java code in the middle and the input JSON is on right. You can see in log the failures.
<img width="1832" alt="image" src="https://user-images.githubusercontent.com/25950902/127171595-5cd99d50-fc88-4099-981b-5148fdcab282.png">

**Comment by JDUNNIN** [comment]
Updating the version to 1.5.8 resolved these issues! Seemed an odd bit of function to be broken at this 1.4.8 but good to resolve it thanks.
