### ISSUE TITLE
Expressions.evaluate() is not thread-safe.

### ISSUE THREAD

**Issue by oldiron-ho** [IBM/JSONata4Java#167]
Test code:

```
   @Test
    void threadSafeTest() throws Exception {
        String json1 = "{ \"a\":\"aaa\" }";
        String json2 = "{ \"a\":\"bbb\" }";
        Expressions exp = Expressions.parse("a");
        // Expressions exp2 = Expressions.parse("a");
        TaskExecutor theExecutor = new SimpleAsyncTaskExecutor();
        theExecutor.execute(new Tester(exp, new ObjectMapper().readTree(json1)));
        theExecutor.execute(new Tester(exp, new ObjectMapper().readTree(json2)));

        while(true) {
            Thread.sleep(1000);
        }
    }

    public class Tester implements Runnable {
        JsonNode data;
        Expressions exp;

        public Tester(Expressions exp,  JsonNode data) {
            this.data = data;
            this.exp = exp;
        }

        @Override
        public void run() {
            while (true) {
                try {
                    JsonNode result = exp.evaluate(data);
                    if (! this.data.get("a").asText().equals(result.asText())) {
                        System.out.println(String.format("%s %s", this.data.get("a").asText(), result.asText()));
                    }
                } catch (Exception ex) {
                    System.out.println(ex);
                }
            }
        }
    }
```
Result is
```
java.lang.NullPointerException
aaa bbb
java.lang.NullPointerException
bbb aaa
bbb aaa
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
...
...
```

I think inner vaiable `_eval` causes unsafety.

https://github.com/IBM/JSONata4Java/blob/c2ec8234ea9a7b0aef706e6c763bd1567ae9a26c/src/main/java/com/api/jsonata4java/expressions/Expressions.java#L54

**Comment by aubelsb2** [comment]
Interesting... I don't have time to work on this now. But I will see if I can get some time allocated to it.

**Comment by aubelsb2** [comment]
A quick look though hints that you're right and the only reason it's there is for testing reasons. I would recommend moving it to the two eval locations and perhaps caching the env/expr per run.

**Comment by wnm3** [comment]
I suspect the NullPointerException is due to the result being null though I am not sure why this would occur.

One problem is the ExpressionsVisitor is being shared by both threads and its steps array gets reset while the other thread is referencing get(0)... which can cause an IndexOutOfBounds exception -- it appears nonsensical as an index of 0 for an array size 1 would not throw the exception:
```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at com.api.jsonata4java.expressions.ExpressionsVisitor.visit(ExpressionsVisitor.java:807)
	at com.api.jsonata4java.expressions.ExpressionsVisitor.visitTree(ExpressionsVisitor.java:2660)
	at com.api.jsonata4java.expressions.Expressions.evaluate(Expressions.java:193)
	at ThreadTester$ThreadTest.run(ThreadTester.java:40)
	at java.lang.Thread.run(Thread.java:748)
```
I suspect what is happening is the method below is being accessed by both threads, one has reset the array when the other attempts to get(0)...
```
	public JsonNode visitTree(ParseTree tree) {
		JsonNode result = null;
		int treeSize = tree.getChildCount();
T2==>		steps.clear();
		for (int i = 0; i < treeSize; i++) {
			steps.add(tree.getChild(i));
		}
		firstStepCons = false;
		lastStepCons = false;
		firstStep = false;
		if (tree.getChildCount() > 0) {
			if (tree.getChild(0) instanceof Array_constructorContext) {
				firstStepCons = true;
			}
			// test for laststep array construction child[n-1] instanceof
			// Array_constructorContext
			ParseTree lastStep = tree.getChild(treeSize - 1);
			if (lastStep instanceof Array_constructorContext) {
				lastStepCons = true;
			}
T1==>			if (tree.equals(steps.get(0))) {
				firstStep = true;
			} else {
				firstStep = false;
			}
		}
		lastVisited = "";
		result = visit(tree);
		if (result != null && result.isDouble()) {
			Double d = result.asDouble();
			if (Double.isInfinite(d) || Double.isNaN(d)) {
				result = JsonNodeFactory.instance.nullNode();
			}
		}
		return result;
	}
```

If your threads had different Expressions (having different ExpressionVisitors) then there is no conflict as you'd seen with exp vs exp2 or with something like:
        theExecutor.execute(new ThreadTest( Expressions.parse("a"), new ObjectMapper().readTree(json1)));
        theExecutor.execute(new ThreadTest( Expressions.parse("a"), new ObjectMapper().readTree(json2)));
so it isn't the execute per se, it is the shared access to the ExpressionVisitor object that is the problem.

I don't think I've ever reused the expression that was parsed across multiple threads. I know in the Tester, I reparse the input object within the while loop.

**Comment by hulapoe** [comment]
Parsing the expression looks to be an expensive operation. it takes almost 180ms. so there's a use case of keeping that expression cached. 

was the thread safety issue resolved when using the same expression across multiple threads?

**Comment by hulapoe** [comment]
I just looked at the very first Expression.parse and that took 180ms , but the subsequent ones took 3ms. nevertheless, you wouldn't want to recreate the expression every time.

**Comment by wnm3** [comment]
I believe the code is thread safe -- I reviewed the static variables and didn't see any issue with them.

Regarding the timing, I wonder if we are seeing a delay on the initial parsing due to class loading delays. If so, this should not be an issue after the initial call to the parser.

**Comment by hulapoe** [comment]
I ran the snippet of code that oldiron-ho had put and it does give different result for the same expression object when multiple threads are running. I would term that as thread safety issue. 

I ran that with synchronized block over the expression object and it did give that issue. I wouldn't like to create an expression object every time for the same expression. also wouldn't like to use synchronized block as it will block the eval call. 

I was planning to use this in the online application with high transaction volume and this can be an issue.

**Comment by wnm3** [comment]
As explained above, the ExpressionVisitor needs to be different for different threads. I'm not sure if I were to make the variables in Expressions and in ExpressionVisitor ThreadLocal if I would introduce more errors that would be harder to trace given what ANTLR is generating for its classes.  You could try this if desired. Again, I believe the overhead you saw with parsing was for the initial class loading and that it would not have the performance penalty you envision after the initial call to parse.

**Comment by oldiron-ho** [comment]
What if we use the synchronized keyword in the evaluate method of Expressions? I tested it with synchronized and confirmed that no errors occur when running the above test code.

```java
    public synchronized JsonNode evaluate(JsonNode rootContext, long timeoutMS, int maxDepth) throws EvaluateException {

    public synchronized JsonNode evaluate(JsonNode rootContext) throws EvaluateException {

```

**Comment by wnm3** [comment]
I'd gotten some pushback to adding synchronized and wondered if your code calling our library could provide the synchronized method wrapping a call to evaluate so your threads could leverage the synchronized call on your method to get the desired protection.

**Comment by oldiron-ho** [comment]
I am currently using the synchronized block to use the evaluate method. However, I was not aware of this issue during development and it was only discovered during testing in a production environment.

Many people using JSONata4Java may not realize this issue until they try running it in a multi-threaded environment. They may assume that, like using Pattern.matcher(), they can compile the pattern once and reuse it multiple times (or simultaneously in a multi-threaded environment).

If it is possible to use the synchronize keyword on the method without causing any other issues, it could help prevent this confusion. Otherwise, it would be helpful to have documentation explaining this issue.

**Comment by oldiron-ho** [comment]
@wnm3 Thank you for your work
