### ISSUE TITLE
ParseException.getMessage() can contain trailing whitespace

### ISSUE THREAD

**Issue by JDUNNIN** [IBM/JSONata4Java#174]
When trying to test `ParseException` method `getMessage()` we found that they could contain a lot of trailing whitespace including a new line (CR ? ). 

E.g for the invalid expression `$count(` we would get a message like (excluding square bracket at start and end just to show whitespace/new line):
```
[line 1:7 at [@2,7:6='<EOF>',<-1>,1:7]: no viable alternative at input '('
    ]
```
Can this be cleaned up to not include the whitespace or call trim() on the getMessage function return value?

**Comment by wnm3** [comment]
This is the output of the ANTLR parser's error. I don't think I'd want to manipulate it as such. I'm sure you could add this finish to your catcher.

**Comment by JDUNNIN** [comment]
OK that makes sense - I'll trim in my codes logic.
