### ISSUE TITLE
Add support for descendant/multi-level wildcard (**.object)

### ISSUE THREAD

**Issue by wnm3** [IBM/JSONata4Java#19]
Add support for the ** wildcard as described in JSONata Documentation [here](https://docs.jsonata.org/predicate#wildcards)

**Comment by ashauer** [comment]
Hi @wnm3,

this is another feature which would be rather important for our use case. Do you have an idea when this will work?

Aloha
Lutz

**Comment by wnm3** [comment]
I will try to get to this later this week. It is a bit more involved as it affects the ANTLR parsing, etc. I'll post status here by Friday CoB. Thanks for the reminder.
