### ISSUE TITLE
!= function when comparing a null value

### ISSUE THREAD

**Issue by Dheeraj3reddy** [IBM/JSONata4Java#192]
When using != function in the expression and say we are comparing lhs with string "str". If lhs is null (say because the lhs is not present in input json) jsonata4java is returning this as true. I tried the same at [jsonata](https://try.jsonata.org/) and it's returning false. I saw through the code for jsonata4java and the logic is written to return true. Could I know the reason behind this.? 
Thanks. 
Consider the following json and expression as an example
`{
  "str" : "val" 
}`
and str1!="val" .

**Comment by wnm3** [comment]
I am having trouble with the sonatype release process so you will need to build your jars using Maven.
Change to the JSONata4Java directory and issue the command:
mvn clean install
then you can go to the target subdirectory to get the jars build for version 1.7.5

**Comment by Dheeraj3reddy** [comment]
It's working as intended. Thanks a lot.
