### ISSUE TITLE
Some Maven dependencies are in the wrong scope

### ISSUE THREAD

**Issue by rbsamoht** [IBM/JSONata4Java#194]
I have noticed that the `org.springframework:spring-context:5.3.19` dependency is not used anywhere in the **main** module of JSONata4Java, but only in the **test** module. This Maven dependency should probably be moved to the test scope to avoid importing many nonrequired transitive dependency on the projects using JSONata4Java.

I suggest that
```
		<dependency>
		    <groupId>org.springframework</groupId>
		    <artifactId>spring-context</artifactId>
		    <version>5.3.19</version>
		</dependency>	
```

should be replaced with:

```
		<dependency>
		    <groupId>org.springframework</groupId>
		    <artifactId>spring-context</artifactId>
		    <version>5.3.19</version>
		    <scope>test</scope>
		</dependency>
```

in the root `pom.xml` file. Doing so would prevent the import of the multiple nonrequired dependencies below:
```
[INFO] +- org.springframework:spring-context:jar:5.3.19:compile
[INFO] |  +- org.springframework:spring-aop:jar:5.3.19:compile
[INFO] |  +- org.springframework:spring-beans:jar:5.3.19:compile
[INFO] |  +- org.springframework:spring-core:jar:5.3.19:compile
[INFO] |  |  \- org.springframework:spring-jcl:jar:5.3.19:compile
[INFO] |  \- org.springframework:spring-expression:jar:5.3.19:compile
```

Also, according to the documentation of [junit 4](https://github.com/junit-team/junit4/wiki/Download-and-Install), the scope of the junit dependency should be **test** scope and not **provided**.

I suggest that

```
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.13.2</version>
			<scope>provided</scope>
		</dependency>
```

should be replaced with:

```
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.13.2</version>
			<scope>test</scope>
		</dependency>
```

in the root `pom.xml` file.

**Comment by wnm3** [comment]
I've added these to the pom.xml as requested and am releasing as version 1.7.8 today. Please close if you are satisfied.

**Comment by rbsamoht** [comment]
Looks good now, thanks for the quick fix!
