### ISSUE TITLE
$max() returns null 

### ISSUE THREAD

**Issue by ghadaobaid** [IBM/JSONata4Java#195]
Given JSON:
````
{
  "predictions": [
    {
      "fields": [
        "prediction",
        "probability"
      ],
      "values": [
        [
          "Some value",
          [
            0.000006837691968266768,
            0.00016754814439838656,
            0.000006131112096258278,
            0.8614282118896663,
            0.1317010806908111,
            0.000006967588338845523,
            0.0007038798767566121,
            0.002561383485534571,
            0.000004593234538122047,
            0.000011076102288301922,
            0.0003259848961316061,
            0.0000653148528980953,
            0.00008930024840494008,
            0.000018742809343110107,
            0.0003201840716758271,
            0.000005968695918318629,
            0.0002543617446606414,
            0.00031095673266523066,
            0.000009501582475308737,
            0.000005378929493706683,
            0.0003025705239998965,
            0.000022157211655980446,
            0.000045727521118372044,
            0.0015245180064875268,
            0.000017677606504370317,
            0.000023757216508315853,
            0.00006018753366163092
          ]
        ]
      ]
    }
  ]
}
````

And Jsonata expression:
````
$max(predictions.values[0][1])
````

**Current Result:**
null node

**Expected Result:**
Numeric node with value 0.8614282118897

**Comment by wnm3** [comment]
I created dataset_c.json to test with and found a workaround that didn't break any of the existing test cases so I'm releasing version 1.7.7 today. You can pull from this repository and build the jars using the following from inside the JSONata4Java directory (where the pom.xml is located):
mvn clean install
then you can find the jar files it produces in the target subdirectory.

**Comment by ghadaobaid** [comment]
That's great - thank you!

**Comment by wnm3** [comment]
Please note I pushed additional content after you'd replied. It will take a couple of hours for the jar to reach Maven Central, but you can check here to see if version 1.7.7 is present:

https://search.maven.org/search?q=g:com.ibm.jsonata4java

**Comment by wnm3** [comment]
If you believe the problem is resolved, please close this issue.

**Comment by ghadaobaid** [comment]
It works now - closing as resolved. Thanks!
