### ISSUE TITLE
Make gpg signing default to off for normal Maven builds, activating only when deploying to Maven Central

### ISSUE THREAD

**Issue by wnm3** [IBM/JSONata4Java#196]
A recent pull request was merged allowing a maven build to detect errors when code is checked in. This fails if signing is attempted as it doesn't have the private key. The pom.xml is edited to make gpg.skip default to true to allow the build to occur, based on this article https://stackoverflow.com/questions/60624285/how-to-set-up-maven-project-to-optionally-generate-signature-files

This will result in a new releases 1.7.8

**Comment by aubelsb2** [comment]
I'll get back to you when I have time to work on this.

**Comment by aubelsb2** [comment]
I can't close this ticket. You initiated it
