### ISSUE TITLE
Build breaks when running under Windows because of failing TestCase in AgnosticeTestSuite

### ISSUE THREAD

**Issue by bluemel** [IBM/JSONata4Java#203]
Failing TestCase is "hof-reduce.case009".

AgnosticeTestSuite line 158 recommends skipping this TestCase on Windows systems
AgnosticeTestSuite line 158:
  SKIP_CASES("hof-reduce", "case010"); // add for windows pending investigation // , "case009");

Reason is system dependent text decoding when reading the TestCase.expr from original JSONata test file with Files.readAllBytes().
The problem occurs because the original JSONata test file contains a Unicode character - a greek lambda.
line 7 of the original JSONata test file jsonata-1.8.4\test\test-suite\groups\hof-reduce:
  $indexof := λ($array, $value) {

Rather than simply reading the bytes and to rely on any OS specific default encoding you should
explicitly apply UTF-8 decoding when reading any of the original JSONata test files - assuming they are all text files.

I've described the fix below. I could also contribute the fix directly to the project if I'd get the
permissions to create a branch and a pull request.

AgnosticeTestSuite line 158:
\- this.expr = new String(Files.readAllBytes(expressionFile.getCanonicalFile().toPath()));
\+ this.expr = readUtf8TextFile(expressionFile.getCanonicalFile().toPath());

New helper method in Agnostice Test Suite:  
private String readUtf8TextFile(Path path) {
  StringBuilder sb = new StringBuilder();
  try (Stream<String> stream = Files.lines(path, StandardCharsets.UTF_8)) {
    stream.forEach(s -> sb.append(s).append("\n"));
  } catch (IOException e) {
    throw new RuntimeException(e);
  }
  return sb.toString();
}

**Comment by wnm3** [comment]
Thank you Martin -- I pushed your changes into AgnosticTestSuite this morning. I'll wait on creating a new version though if okay with you. Please let me know if this fixed the problem for you on Windows.

**Comment by bluemel** [comment]
Thank you, Nat.For sure it will fix the build problem for anyone  who wants to build under Windows since I've already tested it.Another very small problem I had with importing the "project" into my Eclipse IDE (import as Maven project) was that the IDE flagged a build probem because of missing folder resources (under src/main). Creating this folder manually helped but it would be more convenient for anyone importing the project the first time if the "resources" folder would come automatically with the "clone" of the git repository.Best regards,Martin

 
  
  
 
 Am 29.08.22, 15:05 schrieb Nathaniel Mills ***@***.***>:

   
  Thank you Martin -- I pushed your changes into AgnosticTestSuite this morning. I'll wait on creating a new version though if okay with you. Please let me know if this fixed the problem for you on Windows.

**Comment by bluemel** [comment]
I've tested the latast and greatest version on master and the build is now running well also under Windows 10 (at least on my developer box).  One last remark:
Shouldn't we consider to remove or change the comment now in AgnosticTestSuite.java, line 158?
		SKIP_CASES("hof-reduce", "case010"); // add for windows pending investigation // , "case009");
 Since case009 is now running also under Windows it should be obsolete. Maybe who ever wrote this comment should be somehow informed that the "pending investigation" is not necessary anymore since the problem is solved.

**Comment by wnm3** [comment]
Thanks -- I'll remove the comment

**Comment by bluemel** [comment]
THX Nat, think we can close the issue now. Wanted to do this myself but I seem not to have sufficient permissions.

**Comment by wnm3** [comment]
Does the close issue show when you type something -- I believe you can close the issue.

**Comment by bluemel** [comment]
Hmmm... closing worked out now with my 3rd try. Before the Buttons "Cloe with comment" and "Close" showed up but pressing them did not change the issue's state. Anyway.. now we are fine :-)
