### ISSUE TITLE
Index not correct in map function

### ISSUE THREAD

**Issue by hugensnh** [IBM/JSONata4Java#228]
Version: 2.2.0

If i use the map function, $i does not represent the current index but remains the value of the first iteration.
For example;

my expression;

[activities{activityParent: 
    $map($,function($v, $i) {
        {
            "number": ($i+1),
            "activityId" : $v.activityId,
            "params" : ($i+1) = 1 ? "param-for-one" : "param-for-two"
        }})
}]

With this json;

{
  "activities": [
    {
      "activityId": "a021e643-e9e3-4ae3-afdf-5ad028b984fa",
      "activityParent": "43e3b05b-8b9f-42d2-80ed-38b7294710ee",
      "id": "7c8cf666-6c25-42d3-899a-ba74161143d0"
    },
    {
      "activityId": "a3bff694-2308-4e53-9f44-0d0460a8a389",
      "activityParent": "57bbb43e-ee4c-4448-a676-a6f261ccd959",
      "id": "60a4987e-6322-4393-9f28-6cb7c0aa013c"
    },
    {
      "activityId": "51a4553c-7b69-44db-a0d8-e3ca2fbf338e",
      "activityParent": "43e3b05b-8b9f-42d2-80ed-38b7294710ee",
      "id": "d37d12d9-4555-4292-a197-d59066813ff8"
    },
    {
      "activityId": "79f29232-f47c-445e-8e02-2c0d665e38ac",
      "activityParent": "26cfafb1-34c3-4d1f-b973-20535b0b490e",
      "id": "19e6308e-cd4f-4c46-a50e-a9d9eaa52d8f"
    },
    {
      "activityId": "8c91cfc6-8a2d-4fc8-a624-dac0a8d75a3a",
      "activityParent": "d21b315c-a2db-447a-a470-74756365cf5d",
      "id": "003f6c20-a2fd-4458-98cd-287e931a9bd4"
    },
    {
      "activityId": "0f152bff-8021-4296-b73c-ef7fce1dbf7b",
      "activityParent": "d21b315c-a2db-447a-a470-74756365cf5d",
      "id": "7aceeed9-f5ae-4888-9429-5fcf882c7045"
    }
  ]
}

I want to group by activityParent and count the childelements.
the result on try.jsonata.org is what i expect; 

https://try.jsonata.org/o6M-xZ67x

[
  {
    "43e3b05b-8b9f-42d2-80ed-38b7294710ee": [
      {
        "number": 1,
        "activityId": "a021e643-e9e3-4ae3-afdf-5ad028b984fa",
        "params": "param-for-one"
      },
      {
        "number": 2,
        "activityId": "51a4553c-7b69-44db-a0d8-e3ca2fbf338e",
        "params": "param-for-two"
      }
    ],
    "57bbb43e-ee4c-4448-a676-a6f261ccd959": {
      "number": 1,
      "activityId": "a3bff694-2308-4e53-9f44-0d0460a8a389",
      "params": "param-for-one"
    },
    "26cfafb1-34c3-4d1f-b973-20535b0b490e": {
      "number": 1,
      "activityId": "79f29232-f47c-445e-8e02-2c0d665e38ac",
      "params": "param-for-one"
    },
    "d21b315c-a2db-447a-a470-74756365cf5d": [
      {
        "number": 1,
        "activityId": "8c91cfc6-8a2d-4fc8-a624-dac0a8d75a3a",
        "params": "param-for-one"
      },
      {
        "number": 2,
        "activityId": "0f152bff-8021-4296-b73c-ef7fce1dbf7b",
        "params": "param-for-two"
      }
    ]
  }
]

but this is the result i get;

[
   {
      "43e3b05b-8b9f-42d2-80ed-38b7294710ee":[
         {
            "number":1,
            "activityId":"a021e643-e9e3-4ae3-afdf-5ad028b984fa",
            "params":"param-for-one"
         },
         {
            "number":1,
            "activityId":"51a4553c-7b69-44db-a0d8-e3ca2fbf338e",
            "params":"param-for-one"
         }
      ],
      "57bbb43e-ee4c-4448-a676-a6f261ccd959":{
         "number":1,
         "activityId":"a3bff694-2308-4e53-9f44-0d0460a8a389",
         "params":"param-for-one"
      },
      "26cfafb1-34c3-4d1f-b973-20535b0b490e":{
         "number":1,
         "activityId":"79f29232-f47c-445e-8e02-2c0d665e38ac",
         "params":"param-for-one"
      },
      "d21b315c-a2db-447a-a470-74756365cf5d":[
         {
            "number":1,
            "activityId":"8c91cfc6-8a2d-4fc8-a624-dac0a8d75a3a",
            "params":"param-for-one"
         },
         {
            "number":1,
            "activityId":"0f152bff-8021-4296-b73c-ef7fce1dbf7b",
            "params":"param-for-one"
         }
      ]
   }
]

**Comment by bluemel** [comment]
I've investigated the problem a bit. The implementation of the $map() function in JSONata for Java seems to be correct (works out fine also with index in many other cases), but in this case it does not get the expected input which would be 2 times a single JSON object node and 2 times a JSON array.  
  
@wnmills3 Nat, I've pushed a new JUnit test MapFunctionNonParTests.test_issue228() on a new branch [#228-map-function-index](https://github.com/IBM/JSONata4Java/tree/%23228-map-function-index).
Maybe you could find some time to debug this case a figure out why the map function in this case receives 6 time a single JSON object node. Somwhere in between the interpreting code seems to resolve the array.   
Jsonata expression:
```activities
{
    activityParent: $
}```
bahaves the same way in original JSONata and JSONata4Java  
  
@hugensnh  Concerning your mapping problem I found a way that is equally working in JSONata and JSONata for Java and additionally produces an output that will be easier to read:  
https://try.jsonata.org/5oYm23BiO

Maybe that helps.

**Comment by wnm3** [comment]
The problem appears to be that the $map function is just receiving the individual objects from the original array so it is only processing a single element each time and the $i value never goes above 0, resulting in the number: 1 entry. The consolidation of the results is occurring int he visitObject function in ExpressionVisitor where it is iterating through the elements in the object, and constructing the results by grouping them by key into an array of values. The index value wanting to be referenced by the function as $i would be the index being set by the grouping on the line that is updating the linked list in the grouping variable:
```
                    final Map<String, ArrayNode> grouping = new LinkedHashMap<>();
                    for (JsonNode element : context) {
                        _environment.pushContext(element);
                        final JsonNode fieldList = visit(ctx.fieldList());
                        fieldList.fields().forEachRemaining(e -> grouping
                            .computeIfAbsent(e.getKey(), ignore -> factory.arrayNode()).add(e.getValue()));
                        _environment.popContext();
                    }
                    grouping.forEach((k, v) -> object.set(k, unwrapArray(v)));
```
It doesn't make sense to pass a counter as we move through the elements in the context because that would range from 0 to 5 in our example.

It almost seems the order of the operations is wrong and that we'd want to generate the content to be passed to the $map function first to yield the arrays of singletons or doubletons.

For example, we want the output of this expression to be feed to the $map function:
[activities{activityParent: $}]

However, there is no way to referenced the array because the key is a value from prior keys. Can use $each($keys(... either.

This is going to take some time to find a suitable solution though what you provided is a very good workaround.

**Comment by wnm3** [comment]
In jsonata, the $map is getting called with the array of each consolidated entry whereas we are getting called for each of the elements in the original array. Therefore the $map in jsonata is able to identify the index because it gets a 2 element array, then a single element array, etc.

```
arr: [{"activityId":"a021e643-e9e3-4ae3-afdf-5ad028b984fa","activityParent":"43e3b05b-8b9f-42d2-80ed-38b7294710ee","id":"7c8cf666-6c25-42d3-899a-ba74161143d0"},{"activityId":"51a4553c-7b69-44db-a0d8-e3ca2fbf338e","activityParent":"43e3b05b-8b9f-42d2-80ed-38b7294710ee","id":"d37d12d9-4555-4292-a197-d59066813ff8"}]
func_args: [{"activityId":"a021e643-e9e3-4ae3-afdf-5ad028b984fa","activityParent":"43e3b05b-8b9f-42d2-80ed-38b7294710ee","id":"7c8cf666-6c25-42d3-899a-ba74161143d0"},0]
arr: [{"activityId":"a3bff694-2308-4e53-9f44-0d0460a8a389","activityParent":"57bbb43e-ee4c-4448-a676-a6f261ccd959","id":"60a4987e-6322-4393-9f28-6cb7c0aa013c"}]
func_args: [{"activityId":"a3bff694-2308-4e53-9f44-0d0460a8a389","activityParent":"57bbb43e-ee4c-4448-a676-a6f261ccd959","id":"60a4987e-6322-4393-9f28-6cb7c0aa013c"},0]
arr: [{"activityId":"79f29232-f47c-445e-8e02-2c0d665e38ac","activityParent":"26cfafb1-34c3-4d1f-b973-20535b0b490e","id":"19e6308e-cd4f-4c46-a50e-a9d9eaa52d8f"}]
func_args: [{"activityId":"79f29232-f47c-445e-8e02-2c0d665e38ac","activityParent":"26cfafb1-34c3-4d1f-b973-20535b0b490e","id":"19e6308e-cd4f-4c46-a50e-a9d9eaa52d8f"},0]
arr: [{"activityId":"8c91cfc6-8a2d-4fc8-a624-dac0a8d75a3a","activityParent":"d21b315c-a2db-447a-a470-74756365cf5d","id":"003f6c20-a2fd-4458-98cd-287e931a9bd4"},{"activityId":"0f152bff-8021-4296-b73c-ef7fce1dbf7b","activityParent":"d21b315c-a2db-447a-a470-74756365cf5d","id":"7aceeed9-f5ae-4888-9429-5fcf882c7045"}]
func_args: [{"activityId":"8c91cfc6-8a2d-4fc8-a624-dac0a8d75a3a","activityParent":"d21b315c-a2db-447a-a470-74756365cf5d","id":"003f6c20-a2fd-4458-98cd-287e931a9bd4"},0]
func_args: [{"activityId":"51a4553c-7b69-44db-a0d8-e3ca2fbf338e","activityParent":"43e3b05b-8b9f-42d2-80ed-38b7294710ee","id":"d37d12d9-4555-4292-a197-d59066813ff8"},1]
func_args: [{"activityId":"0f152bff-8021-4296-b73c-ef7fce1dbf7b","activityParent":"d21b315c-a2db-447a-a470-74756365cf5d","id":"7aceeed9-f5ae-4888-9429-5fcf882c7045"},1]
[
  {
    "43e3b05b-8b9f-42d2-80ed-38b7294710ee": [
      {
        "number": 1,
        "activityId": "a021e643-e9e3-4ae3-afdf-5ad028b984fa",
        "params": "param-for-one"
      },
      {
        "number": 2,
        "activityId": "51a4553c-7b69-44db-a0d8-e3ca2fbf338e",
        "params": "param-for-two"
      }
    ],
    "57bbb43e-ee4c-4448-a676-a6f261ccd959": {
      "number": 1,
      "activityId": "a3bff694-2308-4e53-9f44-0d0460a8a389",
      "params": "param-for-one"
    },
    "26cfafb1-34c3-4d1f-b973-20535b0b490e": {
      "number": 1,
      "activityId": "79f29232-f47c-445e-8e02-2c0d665e38ac",
      "params": "param-for-one"
    },
    "d21b315c-a2db-447a-a470-74756365cf5d": [
      {
        "number": 1,
        "activityId": "8c91cfc6-8a2d-4fc8-a624-dac0a8d75a3a",
        "params": "param-for-one"
      },
      {
        "number": 2,
        "activityId": "0f152bff-8021-4296-b73c-ef7fce1dbf7b",
        "params": "param-for-two"
      }
    ]
  }
]
```

**Comment by wnm3** [comment]
I believed this is fixed. By deferring execution of the 2nd part of the expression (following the colon) we can process the elements for the path expression then apply the 2nd part of the expression to the results. I merged the branch. If okay we can make a release 2.2.3
