### ISSUE TITLE
Follow up with issue 237 for more places to change 

### ISSUE THREAD

**Issue by zc632995195** [IBM/JSONata4Java#240]
This is the request as the follow-up with my colleague issue few weeks before: https://github.com/IBM/JSONata4Java/issues/237#issuecomment-1329436414 

From the issue he mentioned the places where we use Jackson's asText() to build the context. --> we change it in 1 place, but there are 4 places in the same class: https://github.com/IBM/JSONata4Java/blob/master/src/main/java/com/api/jsonata4java/expressions/utils/FunctionUtils.java#L340 

I put the line number here: line 340, line 468, line 723, line 818. 

We notice this because we define some custom logic for our transformation. For now we have forked our version, and changing those 4 places get our transformation work as expected for special chars..

**Comment by wnm3** [comment]
Thanks Tom, I'll take a look tomorrow. Hopefully it is a simple fix without ripple effects.

**Comment by wnm3** [comment]
@markhiscock I've validated that changing the lines above from asText() to toString() didn't create any issues with the tests. I noticed you were still working on function refactoring so I won't check in the change unless it won't affect your work. If you could make this change in your branch we could incorporate it when you are ready to check in the changes. Thank, Nat

**Comment by bluemel** [comment]
Concerning my current work on the functions... simply consider it as "ongoing". I could issue a pull request from time to time in order to synchronize my current work with master. If the master changes I intend to synchronize my branch by means of a merge. So we can all continue and nobody is blocked.

14.12.2022 18:38:32 Nathaniel Mills ***@***.***>:

**Comment by wnm3** [comment]
Thanks -- pushed the change to master. Will wait for other changes before creating a new version since they have forked a copy.
