### ISSUE TITLE
Please advise how you are using JSONata4Java

### ISSUE THREAD

**Issue by wnm3** [IBM/JSONata4Java#242]
Please add a comment to this issue describing how you are using JSONata4Java. I'd like to receive feedback by 1/31 if possible but this issue could be useful for all repo members to become aware of other ways the code has been / could be used. Thank you in advance. Nat (if you'd prefer to email me directly you can send to wnm3@us.ibm.com)

**Comment by uw4** [comment]
First of all a big thank you + kudos for creating JSONata!

Dashjoin https://github.com/dashjoin/platform is a data centric low-code platform 
that uses JSONata as central engine for "expressions" (for example for ETL pipeline transformations, for GUI widget data mangling, database triggers etc.):
[https://dashjoin.github.io/platform/3.2/developer-reference/#expressions](https://dashjoin.github.io/platform/3.2/developer-reference/#expressions)

This includes a graphical JSONata expression editor, which allows drag&drop to build expressions:
![image](https://user-images.githubusercontent.com/62463897/214555444-d50a8d5b-041a-484f-99d7-b6715e598742.png)

-> sent you PM with more details
