### ISSUE TITLE
nested $filter doesn't work

### ISSUE THREAD

**Issue by hulapoe** [IBM/JSONata4Java#250]
json:
{
  "value": {
    "rslt": {
      "s1": {
        "attribute1": "attr1"
      },
      "s2": {
        "attribute2": "attr2"
      }
    },
    "args": {
      "segments": [
        "s1",
        "s3"
      ]
    }
  }
}

jsonata Expression:
$count($filter($keys(value.rslt), function($v1) { $filter(value.args.segments, function($v2) { $v1 = $v2 })})) > 0

this should return true but Jsonata4Java returns false.

**Comment by wnm3** [comment]
I believe I have fixed this issue and have checked in the fixes. However, I'm having difficulty releasing the jar to Maven Central but will continue trying to do so. In the interim, if you pull my updates from the github repository and use the commands:
```
cd JSONata4Java/JSONata4Java
mvn clean install
```
You will find updated jar files in the target subdirectory.
Please close this issue if you believe it has been fixed.

**Comment by wnm3** [comment]
I was successful releasing to Maven Central so version 2.2.8 should be available in a couple of hours (3/1/23 9:46am ET)

**Comment by hulapoe** [comment]
tested it and it's working in 2.2.8. thanks!
