### ISSUE TITLE
Order By Operator not supported

### ISSUE THREAD

**Issue by bluemel** [IBM/JSONata4Java#255]
Hi Nat,

it seems to me that we are currently not supporting JSONata's  Order By operator.
https://docs.jsonata.org/path-operators#---order-by

E. g.: https://try.jsonata.org/YKVa54Iu_

**Comment by wnm3** [comment]
Correct, we don't currently support this. It is documented at the bottom of the README.md file.

**Comment by bluemel** [comment]
So now we could support this soon 👍

**Comment by wnm3** [comment]
Thank you again Martin -- I really appreciate your contributions. I've released v2.4.0 today. It may take a couple of hours to reach the Maven Central, but the Sonatype repo should have it now.
