### ISSUE TITLE
Different result structures for wrapping evaluation results in array

### ISSUE THREAD

**Issue by JDUNNIN** [IBM/JSONata4Java#30]
Hello,
I've been trying to format the results of an expression so I can work out which object they came from and I've spotted a difference compared to base JSONata. 

Given input data of:
```
{
    "Example": [
        {
            "names": "first"
        },
        {
            "names": "second"
        },
        {
            "names": ["third", "fourth"]
        }
    ]
}
```
When I use expression `Example.[names]` in JSONata exerciser online.

Then I get result as:
```
[
  [
    "first"
  ],
  [
    "second"
  ],
  [
    "third",
    "fourth"
  ]
]
```

When I use the same in Java I get result:
```
[ 
   "first",
   "second", 
   [ 
      "third",
      "fourth" 
   ] 
]
```

Thanks.

**Comment by wnm3** [comment]
Hi, this is difficult. I've tried for two days to address the issue. There is a difference in the way we're parsing and interpreting the expressions, and I'm losing the array. In jsonata.js they process steps and push the intermediate results into an array result object. I'll still try to figure out a solution, but it will take time. Sorry.

**Comment by wnm3** [comment]
Fixed, finally. One of the problems was the original code base was written against jsonata.js version 1.5 that seemed to treat array flattening a bit different than 1.8 does. I believe we are compliant with 1.8. I've added some tests to the release capturing both this issue and #29 to ensure this doesn't break moving forward.

I've pushed to Maven but it won't be available for a couple of hours -- look for release 1.2.3

Please review and close if acceptable.

**Comment by JDUNNIN** [comment]
Hi @wnm3 I've just tested this using `1.2.3` and it works as expected now. Thanks for the fix
