### ISSUE TITLE
Subtle difference in $pad function behaviour

### ISSUE THREAD

**Issue by msmiths** [IBM/JSONata4Java#83]
The `$pad` function throws an EvaluateException when evaluating the following expressions:

    $pad('foo', 10, '#$%^&')

The exception message is:

    Argument 3 of function $pad does not match function signature

The implementation is enforcing that the length of the **char** parameter is <= 2.  However, JavaScript implementation used by the exerciser does not enforce this limitation and returns the following for the same expression:

    "foo#$%^&#$"

**Comment by wnm3** [comment]
There was a typo where padData should have been, it had strData instead. Fixed.

Can be closed as part of release 1.4.4
