### ISSUE TITLE
$trim() function not throwing EvaluateException when passed invalid arguments

### ISSUE THREAD

**Issue by msmiths** [IBM/JSONata4Java#85]
The $trim function is not throwing an EvaluateException when evaluating the following expressions:

    $trim()
    $trim({})
    $trim([])
    $trim({"hello": 1})
    $trim(["hello", 1])
    $trim(1)
    $trim(-22.2)
    $trim(10/3.0)
    $trim(null)

The JavaScript implementation used by the exerciser raises errors for all of the expressions shown above.

**Comment by wnm3** [comment]
$trim() with null context returns null per function-trim:case002 unit test, but $trim() with invalid context throws ERR_BAD_CONTEXT. I fixed this in the TrimFunctionTests.java

This can be closed with the release of 1.4.4
