### ISSUE TITLE
Subtle difference in $split function behaviour

### ISSUE THREAD

**Issue by msmiths** [IBM/JSONata4Java#86]
The $split function throws an EvaluateException when evaluating the following expression:

    $split(' ', {})
    $split(' ', [])
    $split(' ', {"hello": 1})
    $split(' ', [\"hello\", 1])
    $split(' ', true)
    $split(' ', null)

The exception message is:

    The matcher function argument passed to function "$split" does not return the correct object structure

The JavaScript implementation used by the exerciser returns the following for the same expressions:

    Argument 2 of function "split" does not match function signature

**Comment by wnm3** [comment]
Changed the exception being thrown. Added testSplitFunction to BasicExpressionTest

This can be closed with the release of 1.4.4
