### ISSUE TITLE
$replace() function not throwing EvaluateException when passed invalid arguments

### ISSUE THREAD

**Issue by msmiths** [IBM/JSONata4Java#87]
The $replace function is not throwing an EvaluateException when evaluating the following expressions:

    $replace()
    $replace({})
    $replace({}, ' ')
    $replace({}, ' ', ' ')
    $replace([])
    $replace([], ' ')
    $replace([], ' ', ' ')
    $replace({\"hello\": 1})
    $replace({\"hello\": 1}, ' ')
    $replace({\"hello\": 1}, ' ', ' ')
    $replace([\"hello\", 1])
    $replace([\"hello\", 1], ' ')
    $replace([\"hello\", 1], ' ', ' ')
    $replace(true)
    $replace(true, ' ')
    $replace(true, ' ', ' ')
    $replace(null)
    $replace(null, ' ')
    $replace(null, ' ', ' ')
    $replace(5)
    $replace(5, ' ')
    $replace(5, ' ', ' ')
    $replace(-5)
    $replace(-5, ' ')
    $replace(-5, ' ', ' ')
    $replace(10/3.0)
    $replace(10/3.0, ' ')
    $replace(10/3.0, ' ', ' ')
    $replace(a.b.c)
    $replace(a.b.c, ' ')
    $replace(a.b.c, ' ', ' ')

The JavaScript implementation used by the exerciser raises errors for all of the expressions shown above.

**Comment by wnm3** [comment]
Had a typo that tested:
if (argCount >= 1 || argCount <= 4)
rather than
if (argCount >= 1 && argCount <= 4)
So no exception was being thrown. Added tests to BasicEvaluateTests

**Comment by wnm3** [comment]
The order of exceptions seems backwards in jsonata.js as it complains about subsequent arguments even if preceding arguments are bad. I've matched jsonata.js' function though.

Also, for the invalid first parameter, I am returning null to be compatible with the function-replace:case004 as I can not test try.jsonata.org with null input so there it complains about the 2nd parameter for something like $replace(a.b.c). So, I've currently got the tests checking for null for the last three tests.

This can be closed with 1.4.4 when it is released.
